require:
  - standard
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable
  Exclude:
    - public/**/*
    - vendor/**/*

Rails:
  Enabled: true
RSpec:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 5
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Max: 10
